### ISSUE TITLE
Checklist for version 2.0.1

### ISSUE THREAD

**Issue by marcverhagen** [tarsqi/ttk#47]
For version 2.0.1 the following is on the wishlist:

- [x] Add other Tarsqi papers to docs/papers
- [x] Further cleanup and simplification of top-level code (checked off here but the changes are actually made in the develop branch and we will just keep them there for now).
- [x] Check whether source types have a default pipeline (this was mentioned in the old documentation, but they don't)
- [ ] Fix issue https://github.com/tarsqi/ttk/issues/15 (Confirm correctness of character offsets)
- [ ] Fix issue https://github.com/tarsqi/ttk/issues/19 (Documentation updates)
- [x] Fix issue https://github.com/tarsqi/ttk/issues/21 (Test removal of GUTime tmp files on windows)
- [x] Fix issue https://github.com/tarsqi/ttk/issues/23 (Update LinkMerger to use confidence scores)
- [ ] Fix issue https://github.com/tarsqi/ttk/issues/29 (Slinket use of old timeml library slinket)
- [x] Fix issue https://github.com/tarsqi/ttk/issues/32 (Duplicate attribute in TTK format)
- [x] Fix issue https://github.com/tarsqi/ttk/issues/37 (Clarify preprocessor modules)
- [x] Fix issue https://github.com/tarsqi/ttk/issues/38 (Missing link identifiers)
- [x] Cleanup docs, especially tracking and notes
- [ ] Add documentation for the testing and evaluation components

When releasing a new version, also remember to do the following:

- [x] Run utilities/make_documentation.py
- [x] Update documentation, in particular the manual
- [x] Make sure docs/manual/index.html is versioned
- [x] Update README.md
- [x] Add version tag to repository
