### ISSUE TITLE
Checklist for version 2.0.2

### ISSUE THREAD

**Issue by marcverhagen** [tarsqi/ttk#55]
Wish list:

- [x] Fix issue #56 (Do not add identifier to source tags)
- [x] Fix issue #15 (Confirm correctness of character offsets)
- [x] Fix issue #42 (Directory names cannot have spaces in them)
- [ ] Add documentation for the testing and evaluation components (this may be a new minor version rather than a patch version)

When releasing a new version, also remember to do the following:

- [x] Run utilities/make_documentation.py
- [x] Update documentation if needed
- [x] Make sure docs/manual/index.html is versioned
- [x] Upload documentation to TimeML website
- [x] Update README.md
- [x] Update VERSION
- [x] Update CHANGELOG.md
- [x] Run tests and regression tests
- [x] Merge to master branch
- [x] Add version tag to repository by creating a new release
