### ISSUE TITLE
Checklist for new version

### ISSUE THREAD

**Issue by marcverhagen** [tarsqi/ttk#66]
Always do the following:

- [ ] Run utilities/make_documentation.py
- [ ] Update documentation if needed
- [ ] Make sure docs/manual/index.html is versioned
- [ ] Upload documentation to TimeML website
- [ ] Update README.md
- [ ] Update VERSION
- [ ] Update CHANGELOG.md
- [ ] Run tests and regression tests
- [ ] Merge to master branch
- [ ] Add version tag to repository by creating a new release
