### ISSUE TITLE
Release 2.2.0 checklist

### ISSUE THREAD

**Issue by marcverhagen** [tarsqi/ttk#91]
This is intended to be the last minor version before porting to Python 3.

Wish list:

- [x] Fix issue #43 (check pipeline)
- [x] Fix issue #90 (treetagger)
- [ ] Fix issue #88 (LIF format)
- [x] Fix issue #83 (EventCorefBank)
- [x] Fix issue #77 (Knowtator-TTK converter)
- [x] Fix issue #39 (source parameter)

When releasing a new version, also remember to do the following:

- [x] Run utilities/make_documentation.py
- [x] Update documentation if needed
- [x] Make sure docs/manual/index.html is versioned
- [ ] Upload documentation to TimeML website
- [x] Update README.md
- [x] Update VERSION
- [x] Update CHANGELOG.md
- [x] Run tests and regression tests
- [x] Merge to master branch
- [x] Add version tag to repository by creating a new release
